version: '3.8'

services:
  app:
    build:
      context: .
    container_name: api-gateway
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
